# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock.xci
# IP: The module: 'vgaPixelClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaPixelClock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaPixelClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaPixelClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock.xci
# IP: The module: 'vgaPixelClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaPixelClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaPixelClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: u:/Users/hawkejo/Documents/Git/vga_controller/vga_controller.srcs/sources_1/ip/vgaPixelClock/vgaPixelClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vgaPixelClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
