# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4ddr.xdc

# IP: ip/vga_pixel_clock/vga_pixel_clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_pixel_clock || ORIG_REF_NAME==vga_pixel_clock} -quiet] -quiet
